fix: active link, navbar transparency
gevuong/minimal-i18n-with-app-router pull request #33
Opened 2024-08-13 17:37 UTC by a-wong-8

Fixed:
1. active link underline for navbar and footer
2. navbar transparency and footer overrun 

<img width="1552" alt="Screenshot 2024-08-13 at 10 31 50 AM" src="https://github.com/user-attachments/assets/cc1a6250-dc1c-4412-b9bb-b24b3afe7643">
<img width="1552" alt="Screenshot 2024-08-13 at 10 31 45 AM" src="https://github.com/user-attachments/assets/39867939-2e01-4538-8664-3ae572c43c2e">

2024-08-13 18:00 UTC, ridham-virufy approved these changes
Great Work!

2024-08-13 19:49 UTC, gevuong requested changes
Is there a reason why the package lock changes are needed?

2024-08-13 19:50 UTC, gevuong commented on app/[lang]/our-story/page.tsx
> +        <div className="relative bg-gradient-to-b from-black to-[#162b4c] ">
remove whitespace

2024-08-13 22:50 UTC, gevuong commented
can you remove the package lock changes? I still see changes to that file

2024-08-14 01:10 UTC, a-wong-8 commented
> can you remove the package lock changes? I still see changes to that file

@gevuong Can you comment on the lines you want changed? I already tried deleting package json and running npm install. I dont know how to change it back

2024-08-14 04:57 UTC, gevuong commented
@a-wong-8 I think there may be a bug. For example, when starting at the home page, when I select "Publications" in the top navbar, I don't see the underline under "Technology" in the footer. Similarly, if I select 'One Young World' (or any dropdown option under "About Us" except for "About Us") in the top navbar, I don't see the underline under "About Us" in the footer.

2024-08-14 05:14 UTC, a-wong-8 commented
> @a-wong-8 I think there may be a bug. For example, when starting at the home page, when I select "Publications" in the top navbar, I don't see the underline under "Technology" in the footer. Similarly, if I select 'One Young World' (or any dropdown option under "About Us" except for "About Us") in the top navbar, I don't see the underline under "About Us" in the footer.

@gevuong good catch

2024-08-14 15:47 UTC, a-wong-8 commented
@gevuong ready for review.

2024-08-14 19:45 UTC, gevuong approved these changes

2024-08-14 19:47 UTC, merged